version: '3'
services:
  knowledge-graphs-python:
    build:
      context: ./KnowledgeGraphsPython
      args:
        - TORCH_VERSION=${TORCH_VERSION}
        - TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION}
        - TORCHVISION_VERSION=${TORCHVISION_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
    image: knowledge-graphs-python:latest
    container_name: knowledge-graphs-python
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all