version: '3.9'
services:
  python-environment:
    build:
      context: ./PythonEnvironment
      args:
        - TORCH_VERSION=${TORCH_VERSION}
        - TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION}
        - TORCHVISION_VERSION=${TORCHVISION_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
    image: python-environment:latest
    container_name: python-environment

  knowledge-graphs-python:
    build:
      context: ./KnowledgeGraphsPython
    depends_on:
      - python-environment
    image: knowledge-graphs-python:latest
    container_name: knowledge-graphs-python
    ports:
      - "7531:7531"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ${KNOWLEDGE_GRAPHS_DATA_PATH}:/KnowledgeGraphsApp/data


  knowledge-graphs-main:
    build:
      context: ./KnowledgeGraphsJava
    depends_on:
      - knowledge-graphs-python
      - graphdb
    image: knowledge-graphs-main:latest
    container_name: knowledge-graphs-main
    ports:
      - "7530:7530"
    volumes:
      - ${KNOWLEDGE_GRAPHS_DATA_PATH}:/KnowledgeGraphsApp/data


  graphdb:
    image: ontotext/graphdb:10.4.0
    container_name: graphdb
    restart: unless-stopped
    environment:
      - GRAPHDB_HOME=/opt/graphdb/home
    ports:
      - "7200:7200"
    volumes:
      - graphdb-data:/opt/graphdb/home/data


volumes:
  graphdb-data:
    name: graphdb-data
    external: true
