version: '3.9'
services:
  python-environment:
    build:
      context: ./PythonEnvironment
      args:
        - TORCH_VERSION=${TORCH_VERSION}
        - TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION}
        - TORCHVISION_VERSION=${TORCHVISION_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
    image: python-environment:latest
    container_name: python-environment

  aa-extraction:
    build:
      context: ./AAExpansion
    depends_on:
      - python-environment
    image: aa-expansion:latest
    container_name: aa-expansion
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]