version: '3.9'
services:
  python-environment:
    build:
      context: ./PythonEnvironment
      args:
        - TORCH_VERSION=${TORCH_VERSION}
        - TORCHAUDIO_VERSION=${TORCHAUDIO_VERSION}
        - TORCHVISION_VERSION=${TORCHVISION_VERSION}
        - CUDA_VERSION=${CUDA_VERSION}
    image: python-environment:latest
    container_name: python-environment

  aa-extraction:
    build:
      context: ./AAExpansion
    depends_on:
      - python-environment
    image: aa-expansion:latest
    container_name: aa-expansion
    ports:
      - "7531:7531"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ${KNOWLEDGE_GRAPHS_RESOURCES_PATH}/AAExpansion:/KnowledgeGraphsApp/resources

  bertmap:
    build:
      context: ./KnowledgeGraphsPython
    depends_on:
      - python-environment
    image: bertmap:latest
    container_name: bertmap
    ports:
      - "7532:7532"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - ${KNOWLEDGE_GRAPHS_RESOURCES_PATH}/KnowledgeGraphsJava/DOntologies:/KnowledgeGraphsApp/resources


  knowledge-graphs-main:
    build:
      context: ./KnowledgeGraphsJava
    depends_on:
      - aa-extraction
      - bertmap
    image: knowledge-graphs-main:latest
    container_name: knowledge-graphs-main
    ports:
      - "7530:7530"
    volumes:
      - ${KNOWLEDGE_GRAPHS_RESOURCES_PATH}/KnowledgeGraphsJava:/KnowledgeGraphsApp/resources