FROM python-environment:latest

# Set working directory
WORKDIR /KnowledgeGraphApp

# Copy Python application code
COPY . .

# Define the command to run the Python application
CMD ["python", "ConnectionPoint.py"]
