# Dockerfile for Environment Base Image
FROM python:3.8.16

# Set a working directory
WORKDIR /KnowledgeGraphApp

# Install shared libraries
COPY requirements.txt .
RUN pip install -r requirements.txt
