create table if not exists bucket (
	BUCKET_ID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(30),
	PAYMENTDAYS INT,
	DATE_CREATED TIMESTAMP
);


-- ##########   PERSON     ########## --

create table if not exists person (
	PERSON_ID INT PRIMARY KEY,
	SEARCH_KEY VARCHAR(30),
	SECONDARY_ID INT UNIQUE,
	LANGUAGE_ VARCHAR(30),
	GENDER CHAR(1),
	D_CREATED TIMESTAMP,
	D_UPDATED TIMESTAMP,
	DT_LAST_ACTION TIMESTAMP
);

create table if not exists person_extra (
	PERSON_ID INT PRIMARY KEY,
	NATIONALITY VARCHAR(30),
	PERSON_STATUS VARCHAR(30),
	IS_DECEASED BOOLEAN,
	RESIDENCE_COUNTRY VARCHAR(30),
	
	FOREIGN KEY (PERSON_ID) REFERENCES person(PERSON_ID)
);

create table if not exists address (
	ADDRESS_ID INT PRIMARY KEY,
	PERSON_ID INT REFERENCES person(PERSON_ID),
	DT_UPDATED TIMESTAMP,
	SECONDARY_ID INT UNIQUE,
	COUNTRY_CODE VARCHAR(30),
	IS_COMMUNICATION BOOLEAN
);


create table if not exists email (
	EMAIL_ID INT PRIMARY KEY,
	PERSON_ID INT REFERENCES person(PERSON_ID),
	DT_UPDATED TIMESTAMP,
	SECONDARY_ID INT UNIQUE,
	IS_COMMUNICATION BOOLEAN
);

create table if not exists phone (
	PHONE_ID INT PRIMARY KEY,
	PERSON_ID INT REFERENCES person(PERSON_ID),
	DT_UPDATED TIMESTAMP,
	SECONDARY_ID INT UNIQUE,
	IS_COMMUNICATION BOOLEAN
);
-- ################################################# --

-- ##########   CASES     ########## --

create table if not exists cases (
 	CASE_ID INT PRIMARY KEY,
	SECONDARY_ID INT UNIQUE,
	INTEREST FLOAT,
	LENTDATE TIMESTAMP,
	LENTAMOUNT FLOAT,
	LENTINTEREST FLOAT,
	LENTEXPENSES FLOAT,
	LENTINITAMOUNT FLOAT,
	TOTPAYAMOUNT FLOAT,
	TOTPAYINTEREST FLOAT,
	TOTPAYEXPENSES FLOAT,
	SEARCHKEY VARCHAR(30) UNIQUE,
	LASTPAYDATE TIMESTAMP,
	BUCKET_ID INT REFERENCES bucket(BUCKET_ID),
	LASTPAYAMOUNT FLOAT,
	LASTUPDATE TIMESTAMP,
	DATECREATED TIMESTAMP,
	CURRENCY VARCHAR(30),
	CASE_TYPE_ID INT,
	USER_UPDATED INT,
	DT_UPDATED TIMESTAMP,
	BASE_INTEREST_RATE FLOAT,
	LAST_CONTACT_ID INT,
	LAST_ACTION INT,
	LAST_ACTION_DATE TIMESTAMP,
	LAST_ACTION_USER_ID INT

 );

create table if not exists case_exta (
	CASE_ID INT PRIMARY KEY,
	PHASE_ID INT,
	SEGMENT_ID INT,
	BANK_ACCOUNT_NUMBER INT,
	DELAY_DAYS INT,
	RESTRUCTURED INT,
	EXPIRY_DATE TIMESTAMP,
	CURRENT_BRANCH_ID INT,
	ACCOUNTSTATUS VARCHAR(30),
	CONTRACT_NO INT,
	STATEMENT_BALANCE FLOAT,
	AVAILABLE_BALANCE FLOAT,
	STATEMENT_OVERDUE_AMOUNT FLOAT,
	APPROVED_CAPITAL FLOAT,
	LAST_INST_DATE TIMESTAMP,
	STATEMENT_MIN_PAY FLOAT,
	BALANCE_LIMIT FLOAT,
	TOTAL_BALANCE FLOAT,
	OVERDUE_CAPITAL FLOAT,
	OVERDUE_INTEREST FLOAT,
	OVERDUE_EXPENSES FLOAT,
	TOTAL_OUTSTANDING FLOAT,
	PORTFOLIO_CODE VARCHAR(30),
	PAY_REF_NUMBER VARCHAR(30),
	
	FOREIGN KEY (CASE_ID) REFERENCES cases(CASE_ID)
);

create table if not exists case_person_type (
	CASE_PERSON_TYPE_ID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(30),
	CASE_PERSON_TYPE_KEY INT UNIQUE
);

create table if not exists case_person (
	CASE_ID INT NOT NULL,
	PERSON_ID INT NOT NULL,
	CASE_PERSON_TYPE_ID INT REFERENCES case_person_type(CASE_PERSON_TYPE_ID),
	DT_UPDATED TIMESTAMP,
	INACTIVE BOOLEAN,
	SOURCE_ VARCHAR(30),
	
	PRIMARY KEY (CASE_ID, PERSON_ID),
	FOREIGN KEY (PERSON_ID) REFERENCES person(PERSON_ID),
	FOREIGN KEY (CASE_ID) REFERENCES cases(CASE_ID)
);

-- ##########   ACTION     ########## --

create table if not exists actcategory (
	ACTCATEGORY_ID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(30)
);

create table if not exists act_type (
	ACTIONCODE_ID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(30),
	TYPE_ INT,
	ISADMIN BOOLEAN,
	ACT_TYPE_ID INT,
	DEF_ACTCATEGORY_ID INT REFERENCES actcategory(ACTCATEGORY_ID),
	ALLOWS_BACKDATED BOOLEAN,
	SETTLE_PLAN_UUID INT,
	PHONEBEHAVIOR INT,
	ACTION_CONTACT_STATUS VARCHAR(30),
	ACTION_CONTACT_TYPE VARCHAR(30)
);

-- ################################################# --
-- ##########   SETTLEMENT     ########## --

create table if not exists settle_plan (
	SETTLE_PLAN_ID INT PRIMARY KEY,
	NAME_ VARCHAR(30),
	DESCRIPTION VARCHAR(30),
	DATEUPDATED TIMESTAMP,
	USERUPDATED TIMESTAMP,
	MAX_PTPS_WARNING INT,
	MAX_PTPS_MAX_ACCEPTED INT,
	MIN_PTP_DIST_WARNING INT,
	MIN_PTP_DIST_MIN_ACCEPTED INT, 
	MAX_PTP_AMOUNT_WARNING FLOAT,
	MAX_PTP_AMOUNT_MAX_ACCEPTED FLOAT,
	WARN_AMOUNT_PERCENTAGE FLOAT,
	MAX_PTP_DIST_MAX_ACCEPTED INT,
	MAX_PTP_DIST_WARNING INT,
	MAX_FIRST_PTP_DIST_ACCEPTED INT,
	MAX_FIRST_PTP_DIST_WARNING INT,
	MAX_PLAN_DUR_MAX_ACCEPTED INT,
	MAX_PLAN_DUR_WARNING INT,
	APPROVAL_METHOD INT,
	SETTLEMENT_PLAN_TYPE INT,
	INTEREST_RATE FLOAT,
	MINIMUM_INTEREST_RATE_WARNING FLOAT,
	MINIMUM_INTEREST_RATE_ERROR FLOAT
);

create table if not exists msettlement_master (
	SETTLEMENT_MASTER_ID INT PRIMARY KEY,
	STATUS VARCHAR(30),
	CURRENCY VARCHAR(30),
	ACCEPTANCE_LEVEL INT,
	INITIAL_SETTLEMENT_MASTER_ID INT REFERENCES msettlement_master(SETTLEMENT_MASTER_ID),
	UTILISATION_STATUS INT, 
	SETTLE_PLAN_ID INT REFERENCES settle_plan(SETTLE_PLAN_ID),
	INITIAL_AMOUNT FLOAT,
	SETTLE_AMOUNT FLOAT,
	ISWRITEOFF BOOLEAN,
	RELATED_CASES INT,
	INITIAL_BASE_RATE FLOAT,
	FINAL_BASE_RATE FLOAT,
	UTILISATION_STATUS_DATE TIMESTAMP,
	UTILISATION_STATUS_USER_ID INT
);

create table if not exists msettlement_detail (
	SETTLEMENT_DETAIL_ID INT PRIMARY KEY, 
	SETTLEMENT_MASTER_ID INT REFERENCES msettlement_master(SETTLEMENT_MASTER_ID),
	PROMISEDDATE TIMESTAMP,
	PROMISEDAMOUNT FLOAT,
	PAIDAMOUNT FLOAT,
	DT_CREATED TIMESTAMP,
	DT_UPDATED TIMESTAMP
);



create table if not exists contact (
	CONTACT_ID INT PRIMARY KEY,
	ACTIONCODE_ID INT REFERENCES act_type(ACTIONCODE_ID),
	CASE_ID INT REFERENCES cases(CASE_ID),
	USER_ID INT,
	CONTACTDATE TIMESTAMP,
	PAYDATE TIMESTAMP,
	PAYAMOUNT FLOAT,
	RECEITNO VARCHAR(30),
	COST_ FLOAT,
	ENTRYDATE TIMESTAMP,
	ENTRY_USER_ID INT,
	SETTLEMENT_MASTER_ID INT REFERENCES msettlement_master(SETTLEMENT_MASTER_ID),
	PERSON_ID INT REFERENCES person(PERSON_ID),
	CURRENCY_CODE VARCHAR(30),
	DATEUPDATED TIMESTAMP
);

create table if not exists payment (
	PAY_ID INT PRIMARY KEY,
	PAYDATE TIMESTAMP,
	PAYAMOUNT FLOAT,
	CONTACT_ID INT REFERENCES contact(CONTACT_ID),
	CASE_ID INT REFERENCES cases(CASE_ID),
	PAYMENTTYPE VARCHAR(30),
	SDATE TIMESTAMP,
	PAY_KEY INT UNIQUE,
	CURRENCY_CODE VARCHAR(30), 
	DESCRIPTION VARCHAR(30)
);

-- ################################################# --
-- ##########   PRODUCT     ########## --

create table if not exists productcategory (
	PRODUCTCATEGORY_ID INT PRIMARY KEY,
	CODE VARCHAR(30),
	DESCRIPTION VARCHAR(30)
);

create table if not exists productreportcategory (
	PRODUCTREPORTCATEGORY_ID INT PRIMARY KEY,
	DESCRIPTION VARCHAR(30)
);

create table if not exists product (
	PRODUCT_ID INT PRIMARY KEY,
	PRODUCTCATEGORY_ID INT REFERENCES productcategory(PRODUCTCATEGORY_ID),
	CODE VARCHAR(30),
	DESCRIPTION VARCHAR(30),
	PRODUCTREPORTCATEGORY_ID INT REFERENCES productreportcategory(PRODUCTREPORTCATEGORY_ID)
);

-- ################################################# --
-- ##########   QUEUE     ########## --

create table if not exists queue (
	QUEUE_ID INT PRIMARY KEY,
	QUEUE_KEY INT UNIQUE,
	CAPTION VARCHAR(30),
	DESCRIPTION VARCHAR(30),
	CAN_EXPIRE BOOLEAN,
	OWNER_USER INT,
	QUEUE_TYPE INT,
	EXIT_ACTION_CODE INT,
	ORDER_TYPE INT,
	IN_STRATEGY INT,
	WORKING_MODE INT, 
	WORKED_ACTION_CATEGORY INT,
	TOTAL INT,
	WORKED INT,
	EXITED INT,
	REMAINING INT
);

create table if not exists queue_case (
	QUEUE_ID INT NOT NULL,
	CASE_ID INT NOT NULL,
	ACCOUNT_ENTRY_DATE TIMESTAMP, 
	ACCOUNT_ENTRY_RULE_ID INT,
	ACCOUNT_ORDER VARCHAR(30),
	STRATEGY_CASE_ID INT, 
	IS_WORKED BOOLEAN,
	PERSON_ID INT REFERENCES person(PERSON_ID),
	
	PRIMARY KEY(QUEUE_ID, CASE_ID),
	FOREIGN KEY (QUEUE_ID) REFERENCES queue(QUEUE_ID),
	FOREIGN KEY (CASE_ID) REFERENCES cases(CASE_ID)
);
-- ################################################# --

create table if not exists rer_metric (
	CASE_ID INT PRIMARY KEY,
	LAST_SETT_STATUS_ID INT, 
	LAST_SETT_COMB_STATUS_ID INT, 
	SETTLE_ISWRITEOFF BOOLEAN,
	PORTFOLIO_CODE VARCHAR(30),
	CASE_TYPE_ID INT, 
	BUCKET_ID_PREV INT REFERENCES bucket(BUCKET_ID),
	PRODUCTCATEGORY_ID INT REFERENCES productcategory(PRODUCTCATEGORY_ID), 
	TOTAL_BALANCE FLOAT,
	TIMES_IN_COLLECTION INT,
	STRATEGY_SEGMENT_ID INT,
	PRODUCT_ID INT REFERENCES product(PRODUCT_ID),
	PRODUCTREPORTCATEGORY_ID INT REFERENCES productreportcategory(PRODUCTREPORTCATEGORY_ID),
	CLIENT_ID INT REFERENCES person(PERSON_ID), 
	PAST_DUE_AMOUNT FLOAT,
	LAST_SETTLE_DATE TIMESTAMP,
	LAST_PAY_DATE TIMESTAMP,
	LAST_PAY_AMOUNT FLOAT,
	LAST_BILLING_DATE TIMESTAMP,
	EXPIRY_DATE TIMESTAMP,
	DAYS_FROM_LAST_PAY INT, 
	DAYS_PAST_DUE INT,
	DAYS_IN_PHASE INT,
	DAYS_IN_COLLECTION INT, 
	PHASE_ENTRY_DATE TIMESTAMP,
	PHASE_ID INT,
	CURRENT_BRANCH_ID INT,
	CURRENCY_ID INT,
	CONTRACT_DATE TIMESTAMP,
	BUCKET_ID INT REFERENCES bucket(BUCKET_ID),
	ACCOUNT_STATUS VARCHAR(30),
	NO_VALID_PHONE BOOLEAN,
	NO_VALID_ADDRESS BOOLEAN,
	BALANCE_LIMIT FLOAT,
	DAYS_IN_HANDLING_QUEUE INT, 
	TOTAL_OUTSTANDING FLOAT,
	
	FOREIGN KEY (CASE_ID) REFERENCES cases(CASE_ID)
);


